# Generated by Django 6.0.7 on 2026-07-27 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='action_items',
            field=models.TextField(blank=True),
        ),
    ]
